version: "3"
services:
  messor:
    container_name: ${CONTAINER_NAME}
    tty: true
    build:
      network: host
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
    - ./data:/app/data
    - ./logs:/app/logs
    ports:
      - 8585:8585
    restart: always
    networks:
      - portainer_default
      - messor
      - rabbitmq
networks:
  messor:
    name: messor
    driver: bridge
  rabbitmq:
    name: rabbitmq
    driver: bridge
    external: true
  portainer_default:
    name: portainer_default
    driver: bridge
    external: true
